// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanetShoes.Infrastructure.Context;

#nullable disable

namespace PlanetShoes.Migrations
{
    [DbContext(typeof(PlanetShoesDbContext))]
    [Migration("20250112103012_UpdateTableEstrutura")]
    partial class UpdateTableEstrutura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.Estrutura", b =>
                {
                    b.Property<string>("IdEstrutura")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdSubEstrutura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeEstrutura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEstrutura")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("IdEstrutura");

                    b.ToTable("Estruturas");

                    b.HasDiscriminator<string>("TipoEstrutura").HasValue("Estrutura");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.MateriaPrima", b =>
                {
                    b.Property<string>("IdMateriaPrima")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Classe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImgMateriaPrima")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnidadeMedida")
                        .HasColumnType("int");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdMateriaPrima");

                    b.ToTable("MateriasPrimas");

                    b.HasData(
                        new
                        {
                            IdMateriaPrima = "MateriaPrima1",
                            Classe = "Natural",
                            Codigo = 0,
                            Descricao = "Couro de alta qualidade",
                            Nome = "Couro Bovino",
                            UnidadeMedida = 2,
                            Valor = 100.00m
                        },
                        new
                        {
                            IdMateriaPrima = "MateriaPrima2",
                            Classe = "Sintético",
                            Codigo = 0,
                            Descricao = "Borracha para solados",
                            Nome = "Borracha Sintética",
                            UnidadeMedida = 5,
                            Valor = 50.00m
                        });
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.Peca", b =>
                {
                    b.Property<string>("IdPeca")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Agrupamento")
                        .HasColumnType("int");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<float>("Consumo")
                        .HasColumnType("real");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("IdEstrutura")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdMateriaPrima")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImgPeca")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MateriaPrimaIdMateriaPrima")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tamanho")
                        .HasColumnType("int");

                    b.HasKey("IdPeca");

                    b.HasIndex("IdEstrutura");

                    b.HasIndex("MateriaPrimaIdMateriaPrima");

                    b.ToTable("Pecas");

                    b.HasDiscriminator().HasValue("Peca");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            IdPeca = "PecaGenerica1",
                            Agrupamento = 0,
                            Codigo = 301,
                            Consumo = 1f,
                            Descricao = "Peça genérica 1",
                            IdEstrutura = "Estrutura9",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Peça Genérica 1",
                            Tamanho = 40
                        },
                        new
                        {
                            IdPeca = "PecaGenerica2",
                            Agrupamento = 1,
                            Codigo = 302,
                            Consumo = 1.5f,
                            Descricao = "Peça genérica 2",
                            IdEstrutura = "Estrutura10",
                            IdMateriaPrima = "MateriaPrima2",
                            ImgPeca = new byte[0],
                            Nome = "Peça Genérica 2",
                            Tamanho = 42
                        });
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.Usuario", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UserId = "9d340277-2ced-4037-84f4-c6fc2cba5579",
                            DisplayName = "Inacio Felipe Couto Ferreira",
                            Email = "inacio.felipe@planetshoes.com",
                            Password = "inacio",
                            Username = "Inacio"
                        },
                        new
                        {
                            UserId = "f9921ce6-ff36-4757-b3be-a7c7e53c45a2",
                            DisplayName = "Luciano Antônio Ferreira",
                            Email = "luciano.ferreira@planetshoes.com",
                            Password = "luciano",
                            Username = "Luciano"
                        });
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.SubEstruturaAcabado", b =>
                {
                    b.HasBaseType("PlanetShoes.Infrastructure.Data.Estrutura");

                    b.Property<float>("Consumo")
                        .HasColumnType("real");

                    b.Property<string>("EstruturaIdEstrutura")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("ImgAcabado")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasIndex("EstruturaIdEstrutura");

                    b.HasDiscriminator().HasValue("Acabado");

                    b.HasData(
                        new
                        {
                            IdEstrutura = "Estrutura1",
                            IdSubEstrutura = "SubEstrutura1",
                            Consumo = 10.5f,
                            ImgAcabado = new byte[0]
                        },
                        new
                        {
                            IdEstrutura = "Estrutura2",
                            IdSubEstrutura = "SubEstrutura2",
                            Consumo = 15f,
                            ImgAcabado = new byte[0]
                        });
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.SubEstruturaAviamento", b =>
                {
                    b.HasBaseType("PlanetShoes.Infrastructure.Data.Estrutura");

                    b.Property<float>("Consumo")
                        .HasColumnType("real");

                    b.Property<string>("EstruturaIdEstrutura")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("ImgAcabado")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasIndex("EstruturaIdEstrutura");

                    b.ToTable("Estruturas", t =>
                        {
                            t.Property("Consumo")
                                .HasColumnName("SubEstruturaAviamento_Consumo");

                            t.Property("EstruturaIdEstrutura")
                                .HasColumnName("SubEstruturaAviamento_EstruturaIdEstrutura");

                            t.Property("ImgAcabado")
                                .HasColumnName("SubEstruturaAviamento_ImgAcabado");
                        });

                    b.HasDiscriminator().HasValue("Aviamento");

                    b.HasData(
                        new
                        {
                            IdEstrutura = "Estrutura3",
                            IdSubEstrutura = "SubEstrutura3",
                            Consumo = 5f,
                            ImgAcabado = new byte[0]
                        },
                        new
                        {
                            IdEstrutura = "Estrutura4",
                            IdSubEstrutura = "SubEstrutura4",
                            Consumo = 7.5f,
                            ImgAcabado = new byte[0]
                        });
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.SubEstruturaComPeca", b =>
                {
                    b.HasBaseType("PlanetShoes.Infrastructure.Data.Estrutura");

                    b.Property<string>("EstruturaIdEstrutura")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("ImgSubEstruturaComPeca")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasIndex("EstruturaIdEstrutura");

                    b.ToTable("Estruturas", t =>
                        {
                            t.Property("EstruturaIdEstrutura")
                                .HasColumnName("SubEstruturaComPeca_EstruturaIdEstrutura");
                        });

                    b.HasDiscriminator().HasValue("ComPeca");

                    b.HasData(
                        new
                        {
                            IdEstrutura = "Estrutura9",
                            IdSubEstrutura = "SubEstrutura9",
                            ImgSubEstruturaComPeca = new byte[0]
                        },
                        new
                        {
                            IdEstrutura = "Estrutura10",
                            IdSubEstrutura = "SubEstrutura10",
                            ImgSubEstruturaComPeca = new byte[0]
                        });
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.PecaCabedal", b =>
                {
                    b.HasBaseType("PlanetShoes.Infrastructure.Data.Peca");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<string>("NomeModelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Perimetro")
                        .HasColumnType("real");

                    b.Property<float>("Superficie")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("PecaCabedal");

                    b.HasData(
                        new
                        {
                            IdPeca = "PecaCabedal1",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "Cabedal de couro",
                            IdEstrutura = "Estrutura5",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Cabedal 1",
                            Tamanho = 40,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Empire",
                            Perimetro = 50f,
                            Superficie = 100f
                        },
                        new
                        {
                            IdPeca = "PecaCabedal2",
                            Agrupamento = 1,
                            Codigo = 102,
                            Consumo = 3f,
                            Descricao = "Cabedal sintético",
                            IdEstrutura = "Estrutura5",
                            IdMateriaPrima = "MateriaPrima2",
                            ImgPeca = new byte[0],
                            Nome = "Cabedal 2",
                            Tamanho = 42,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Modern",
                            Perimetro = 55f,
                            Superficie = 110f
                        },
                        new
                        {
                            IdPeca = "786E20A8-C63B-4DDB-82F7-77746E608F6E",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Lateral",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "E5F4B02A-7C69-469A-86FF-C6E552643373",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Frente",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "7D820DD4-F558-423C-804C-4AC12F9491C0",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Lingua",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "1B183DD2-3629-44E1-A135-1CF173A960CB",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "ContraForte",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "D370D1C3-E7C5-40AB-9E99-634D564088FD",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Estrutura",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "940C7C4A-632A-4728-877B-89863C2BF36F",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Regorço Tesourinha",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "238DEEE8-ACDB-43E3-B468-FE2EB0D4A2CD",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Tubox",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "D23A4A71-53CF-45EA-88E4-FDAEDF03158B",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Palmilha Acabamento",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "BE2E37D0-01CF-4C58-A9CE-2612571B8A9A",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Palmilha Montagem",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "A3150C99-045A-4EA9-8583-866233CE1F18",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Cunho Palmilha",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "81598CCB-AEE0-4448-9106-8226BC54E2AE",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Ilhos",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "1D39D7E3-F75E-4611-AF5D-6B66012ECFDF",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "ColaPesponto",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "D9A9C947-1A63-4496-920E-64BBF4ED83E1",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Palmilha Acabamento",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "32E9988E-6969-4209-9BF6-90AC2BD4FE79",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Tubox",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "D1D37C29-5759-443D-AC2B-1118F734FF8D",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Etiqueta Lingua",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "6B4B84E7-47B8-4E0D-A575-D27F8E21EDB4",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Viés",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "34391FA0-DF9D-450B-A61D-9F07929D27DF",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Tubox",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "A55D8AB8-F77E-4BEA-8BAE-3AD36930606A",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Linha Biqueira",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "83BEFC4D-6572-47C7-B2D1-D36B7E7DD024",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Linha Viés Lingua",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "83FDF359-85CA-45C8-AEEE-B4D7D7DD8EE7",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Linha Contra Forte",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "81EC7B9A-D5D8-4334-A4E2-F994D0CF352E",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Linha Viés Cabedal",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        },
                        new
                        {
                            IdPeca = "B963687B-8253-47F6-8EAC-4B0247FF14D1",
                            Agrupamento = 0,
                            Codigo = 101,
                            Consumo = 2.5f,
                            Descricao = "",
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Linha Canelinha",
                            Tamanho = 39,
                            Data = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 0, 0, 0, 0),
                            NomeModelo = "Tradition",
                            Perimetro = 0f,
                            Superficie = 0f
                        });
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.PecaSolado", b =>
                {
                    b.HasBaseType("PlanetShoes.Infrastructure.Data.Peca");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("PecaSolado");

                    b.HasData(
                        new
                        {
                            IdPeca = "PecaSolado1",
                            Agrupamento = 0,
                            Codigo = 201,
                            Consumo = 1.5f,
                            Descricao = "Solado de borracha",
                            IdEstrutura = "Estrutura5",
                            IdMateriaPrima = "MateriaPrima2",
                            ImgPeca = new byte[0],
                            Nome = "Solado 1",
                            Tamanho = 40,
                            Peso = 0.5f
                        },
                        new
                        {
                            IdPeca = "PecaSolado2",
                            Agrupamento = 1,
                            Codigo = 202,
                            Consumo = 2f,
                            Descricao = "Solado de EVA",
                            IdEstrutura = "Estrutura8",
                            IdMateriaPrima = "MateriaPrima1",
                            ImgPeca = new byte[0],
                            Nome = "Solado 2",
                            Tamanho = 42,
                            Peso = 0.6f
                        });
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.SubEstruturaComPecaCabedal", b =>
                {
                    b.HasBaseType("PlanetShoes.Infrastructure.Data.SubEstruturaComPeca");

                    b.Property<int>("DesignCabedal")
                        .HasColumnType("int");

                    b.Property<int>("EstruturaCabedal")
                        .HasColumnType("int");

                    b.ToTable("Estruturas", t =>
                        {
                            t.Property("EstruturaIdEstrutura")
                                .HasColumnName("SubEstruturaComPeca_EstruturaIdEstrutura");
                        });

                    b.HasDiscriminator().HasValue("ComPecaCabedal");

                    b.HasData(
                        new
                        {
                            IdEstrutura = "Estrutura5",
                            IdSubEstrutura = "SubEstrutura5",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 2,
                            EstruturaCabedal = 1
                        },
                        new
                        {
                            IdEstrutura = "Estrutura6",
                            IdSubEstrutura = "SubEstrutura6",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 1,
                            EstruturaCabedal = 2
                        },
                        new
                        {
                            IdEstrutura = "01D87D95-6249-4498-9DDA-A02DC6E42289",
                            IdSubEstrutura = "F6E11985-8E4E-48E4-B2CC-D465D000346E",
                            NomeEstrutura = "Tradition",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 2,
                            EstruturaCabedal = 4
                        },
                        new
                        {
                            IdEstrutura = "A035415C-2E66-488C-B71A-ABFDC01C563B",
                            IdSubEstrutura = "706DB229-FBDE-4DC8-809F-4438A04466C2",
                            NomeEstrutura = "New Stone 7010",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 2,
                            EstruturaCabedal = 2
                        },
                        new
                        {
                            IdEstrutura = "E8239707-2A14-4E06-AA4C-58ED9A42EFB9",
                            IdSubEstrutura = "4BA8CDC6-E596-428D-85AC-59407F2C2F87",
                            NomeEstrutura = "Winner 7010",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 2,
                            EstruturaCabedal = 2
                        },
                        new
                        {
                            IdEstrutura = "29FBB68A-5082-4DA0-B0A9-C7CCA1F74863",
                            IdSubEstrutura = "58888D1E-ACB8-4C21-ADAE-4FA045BDABC2",
                            NomeEstrutura = "Jupter infanatil",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 1,
                            EstruturaCabedal = 3
                        },
                        new
                        {
                            IdEstrutura = "82B642A3-49E5-44E1-BF4C-6DB5A5D32E2E",
                            IdSubEstrutura = "64DDEF39-2D7F-4536-9384-EF38A3BCAF64",
                            NomeEstrutura = "Orion infantil",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 1,
                            EstruturaCabedal = 3
                        },
                        new
                        {
                            IdEstrutura = "5B26036A-093A-4281-B7F9-2FC8E279BA9B",
                            IdSubEstrutura = "614D36C0-BB73-4A47-81DC-53CA4E84EABF",
                            NomeEstrutura = "Vintage",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 1,
                            EstruturaCabedal = 3
                        },
                        new
                        {
                            IdEstrutura = "70C8D67F-8389-4A0F-B562-B65755BF5F2D",
                            IdSubEstrutura = "E866DA20-6D2C-4DB8-8CAE-87E0583E0976",
                            NomeEstrutura = "Icaro",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 1,
                            EstruturaCabedal = 3
                        },
                        new
                        {
                            IdEstrutura = "B7DCEF23-1A4D-4107-8E09-5D77C4C7D672",
                            IdSubEstrutura = "9DE1CFEF-3CC5-41D7-899A-CB6CFA9E097D",
                            NomeEstrutura = "Emma",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 1,
                            EstruturaCabedal = 2
                        },
                        new
                        {
                            IdEstrutura = "D98C37D8-EBA7-4C56-8C2D-D1F09900968D",
                            IdSubEstrutura = "50606EB5-86C1-40CA-A6A1-820E050DE4BA",
                            NomeEstrutura = "Rock",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 1,
                            EstruturaCabedal = 2
                        },
                        new
                        {
                            IdEstrutura = "6A041E67-E930-4C90-A5B5-4E6FFFDD9B4D",
                            IdSubEstrutura = "0776F178-C54A-4510-9071-B3BCD8949294",
                            NomeEstrutura = "Ivy",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 1,
                            EstruturaCabedal = 2
                        },
                        new
                        {
                            IdEstrutura = "EF8F52BD-03C8-431B-8BBF-53E312E667CE",
                            IdSubEstrutura = "84EB0992-FF2B-4C17-AD84-884B5396C26C",
                            NomeEstrutura = "Los Angeles Cano Baixo",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 1,
                            EstruturaCabedal = 4
                        },
                        new
                        {
                            IdEstrutura = "8DBD4389-489A-420E-951D-8E10692C66C7",
                            IdSubEstrutura = "BBC0A289-83D4-4021-AF66-E8137C9AD0FE",
                            NomeEstrutura = "Maya Frequencia",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 1,
                            EstruturaCabedal = 3
                        },
                        new
                        {
                            IdEstrutura = "890A6467-11F0-4F24-AB71-1DA78E7557DC",
                            IdSubEstrutura = "4EDDBF84-E910-45D9-9F5A-1D438A4C6079",
                            NomeEstrutura = "Empire",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 1,
                            EstruturaCabedal = 3
                        },
                        new
                        {
                            IdEstrutura = "4FCC9FBE-2E74-49EE-894B-CD0218DEE4FC",
                            IdSubEstrutura = "731C10FA-2FE5-46FC-AAB3-EF9C698AFCE5",
                            NomeEstrutura = "Pegasus",
                            ImgSubEstruturaComPeca = new byte[0],
                            DesignCabedal = 1,
                            EstruturaCabedal = 3
                        });
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.SubEstruturaComPecaSolado", b =>
                {
                    b.HasBaseType("PlanetShoes.Infrastructure.Data.SubEstruturaComPeca");

                    b.Property<int>("AlturaSolado")
                        .HasColumnType("int");

                    b.Property<int>("DesignSolado")
                        .HasColumnType("int");

                    b.Property<int>("EstruturaSolado")
                        .HasColumnType("int");

                    b.ToTable("Estruturas", t =>
                        {
                            t.Property("EstruturaIdEstrutura")
                                .HasColumnName("SubEstruturaComPeca_EstruturaIdEstrutura");
                        });

                    b.HasDiscriminator().HasValue("ComPecaSolado");

                    b.HasData(
                        new
                        {
                            IdEstrutura = "Estrutura7",
                            IdSubEstrutura = "SubEstrutura7",
                            ImgSubEstruturaComPeca = new byte[0],
                            AlturaSolado = 2,
                            DesignSolado = 1,
                            EstruturaSolado = 0
                        },
                        new
                        {
                            IdEstrutura = "Estrutura8",
                            IdSubEstrutura = "SubEstrutura8",
                            ImgSubEstruturaComPeca = new byte[0],
                            AlturaSolado = 3,
                            DesignSolado = 4,
                            EstruturaSolado = 1
                        });
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.Peca", b =>
                {
                    b.HasOne("PlanetShoes.Infrastructure.Data.SubEstruturaComPeca", null)
                        .WithMany("Pecas")
                        .HasForeignKey("IdEstrutura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanetShoes.Infrastructure.Data.MateriaPrima", "MateriaPrima")
                        .WithMany()
                        .HasForeignKey("MateriaPrimaIdMateriaPrima");

                    b.Navigation("MateriaPrima");
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.SubEstruturaAcabado", b =>
                {
                    b.HasOne("PlanetShoes.Infrastructure.Data.Estrutura", null)
                        .WithMany("SubEstruturasAcabado")
                        .HasForeignKey("EstruturaIdEstrutura");
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.SubEstruturaAviamento", b =>
                {
                    b.HasOne("PlanetShoes.Infrastructure.Data.Estrutura", null)
                        .WithMany("SubEstruturasAviamento")
                        .HasForeignKey("EstruturaIdEstrutura");
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.SubEstruturaComPeca", b =>
                {
                    b.HasOne("PlanetShoes.Infrastructure.Data.Estrutura", null)
                        .WithMany("SubEstruturasComPeca")
                        .HasForeignKey("EstruturaIdEstrutura");
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.Estrutura", b =>
                {
                    b.Navigation("SubEstruturasAcabado");

                    b.Navigation("SubEstruturasAviamento");

                    b.Navigation("SubEstruturasComPeca");
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.SubEstruturaComPeca", b =>
                {
                    b.Navigation("Pecas");
                });
#pragma warning restore 612, 618
        }
    }
}
