// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanetShoes.Infrastructure.Data;

#nullable disable

namespace PlanetShoes.Migrations
{
    [DbContext(typeof(PlanetShoesDbContext))]
    partial class PlanetShoesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.MateriaPrima", b =>
                {
                    b.Property<string>("IdMateriaPrima")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Classe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImgMateriaPrima")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeMedida")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdMateriaPrima");

                    b.ToTable("MateriasPrimas");
                });

            modelBuilder.Entity("PlanetShoes.Infrastructure.Data.Usuario", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UserId = "9d340277-2ced-4037-84f4-c6fc2cba5579",
                            DisplayName = "Inacio Felipe Couto Ferreira",
                            Email = "inacio.felipe@planetshoes.com",
                            Password = "inacio",
                            Username = "Inacio"
                        },
                        new
                        {
                            UserId = "f9921ce6-ff36-4757-b3be-a7c7e53c45a2",
                            DisplayName = "Luciano Antônio Ferreira",
                            Email = "luciano.ferreira@planetshoes.com",
                            Password = "luciano",
                            Username = "Luciano"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
